src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.url')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/base/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField


# from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Post(models.Model):
    objects = None
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="placeholder.png")
    body = RichTextField(null=True, blank=True)
    created = models.TimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)
    slug = models.SlugField(null=True, blank=True)
    git = models.URLField(verbose_name=None, name=None, null=True)

    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):

        if self.slug is None:
            slug = slugify(self.headline)
            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug

        super().save(*args, **kwargs)

src/base/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

src/base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
# Create your views here.
from .models import Post
from .forms import PostForm
from .filters import PostFilter


def home(request):
    posts = Post.objects.filter(active=True, featured=True)[0:3]

    context = {'posts': posts}
    return render(request, 'base/index.html', context)


def posts(request):
    posts = Post.objects.filter(active=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs

    page = request.GET.get('page')
    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'myFilter':myFilter}
    return render(request, 'base/posts.html', context)


def post(request, slug):
    post = Post.objects.get(slug=slug)
    context = {'post': post}
    return render(request, 'base/post.html', context)


def profile(request):
    return render(request, 'base/profile.html')


# CRUD VIEWS
@login_required(login_url='home')
def create(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')
    context = {'form': form}
    return render(request, 'base/create.html', context)


@login_required(login_url='home')
def update(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')
    context = {'form': form}
    return render(request, 'base/create.html', context)


@login_required(login_url='home')
def delete(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method == 'POST':
        post.delete()
        return redirect('posts')
    context = {'item': post}
    return render(request, 'base/delete.html', context)


def sendEmail(request):

    if request.method == 'POST':
        template = render_to_string('base/email_template.html',
                                    {'name': request.POST['name'],
                                     'email': request.POST['email'],
                                     'message': request.POST['message'],
                                     })

        email = EmailMessage(
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['khalil.guesmi96@gmail.com'])
        email.fail_silently = False
        email.send()
    return render(request, 'base/email_sent.html')

src/base/templates/base/create.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">

    <style type="text/css">
        #div_id_tags > div{
            max-height: 100px;
            overflow-y: scroll;
            border:1px solid #888;
            padding: 5px;
            border-radius: 5px;
        }
    </style>


    <div class="main-container">
          <h3>Create Post</h3>

          <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <input class="btn btn-primary" type="submit" value="Submit Post">
          </form>
    </div>
{% endblock content %}

src/base/templates/base/delete.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <style type="text/css">
        #div_id_tags > div{
            max-height: 100px;
            overflow-y: scroll;
            border:1px solid #888;
            padding: 5px;
            border-radius: 5px;
        }
    </style>
        <div class="main-container">
              <h3>Delete Post</h3>

              <form method="POST" action="">
                {% csrf_token %}
                <p> Are you sure you want to delete {{item}} ?</p>

                <input class="btn btn-danger" type="submit" value="Confirm">
              </form>
        </div>
{% endblock content %}

src/base/templates/base/email_sent.html
{% extends 'base/main.html' %}

{% block content %}
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Thanks for reaching out!</h1>
		<p>Your message was successfully sent. I will do my best to get back to you in a timely manner :)</p>
		<a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
	</div>
</div>

{% endblock content %}

src/base/templates/base/email_template.html
{{message}}

{{name}}

{{email}}

src/base/templates/base/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>

</body>
</html>

src/base/templates/base/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Khalil Guesmi</title>


	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap"
		  rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">

</head>
<body>

	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm Khalil Guesmi</h1>
			</div>


			<div class="intro-wrapper">
				{% include 'base/navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/IMG_3794.png'%}">
					<h5 style="text-align: center;line-height: 0;">Personalize Theme</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Theme settings will be saved for<br>your next vist</p>
				</div>

				<div class="right-column">

					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>Electrical and Automatic Engineer</h3>

							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>More about me</h4>

					<p>I am a young graduate with a capacity for adaptation and skills that have always motivated
					me to improve my career.</p>

					<p>Motivation, discipline and listening are the watchwords of my professional behaviour.</p>


					<hr>

					<h4>COMPUTER SKILLS</h4>



					<div id="skills">
						<ul>
							<li>TIA Portal</li>
							<li>STEP 7</li>
							<li>Omron </li>
							<li>AutoCAD</li>
							<li>Factory I/O</li>
						</ul>

						<ul>
							<li>MATLAB</li>
							<li>Python</li>
							<li>Django</li>
							<li>Node-RED</li>
							<li>C</li>
						</ul>


					</div>
					<h4>CURRICULUM VITAE</h4>
					<p>you can find my curriculum vitae here: <a target="_blank"
				 	href="{% static 'CV_Khalil_Guesmi (EN).pdf' %}">Download Resume</a></p>

				</div>

				
				<div class="social-links">
					<img id="social_img" src="{% static 'images/linkedin-github.png' %}">
					<h3>Find me on LinkedIn & GitHub</h3>

					<a target="_blank" href="https://www.linkedin.com/in/khalil-guesmi-39072121b/">
					<svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" viewBox="0 0 34 34"
						 class="global-nav__logo">
						<title>
        				LinkedIn
      					</title>
      					<g>
      						<path d="M34,2.5v29A2.5,2.5,0,0,1,31.5,34H2.5A2.5,2.5,0,0,1,0,31.5V2.5A2.5,2.5,0,0,1,2.5,0h29A2.5,2.5,0,0,1,34,2.5ZM10,13H5V29h5Zm.45-5.5A2.88,2.88,0,0,0,7.59,4.6H7.5a2.9,2.9,0,0,0,0,5.8h0a2.88,2.88,0,0,0,2.95-2.81ZM29,19.28c0-4.81-3.06-6.68-6.1-6.68a5.7,5.7,0,0,0-5.06,2.58H17.7V13H13V29h5V20.49a3.32,3.32,0,0,1,3-3.58h.19c1.59,0,2.77,1,2.77,3.52V29h5Z" fill="currentColor"></path>
      					</g>
    				</svg>
						Khalil Guesmi
					</a>
					<br>
					<a target="_blank" href="https://github.com/khalilguesmi96">
					<img class="Qries"  src="{%static 'images/GitHub.jpg' %}">
						khalilguesmi96

					</a>
				</div>
			</div>

		</div>
	</section>

	<section class="s1">
			<div class="main-container">
				<h3 style="text-align: center;">Some of my past projects</h3>

				<div class="post-wrapper">
					{% for post in posts %}
					<div style="text-align:center">
						<div class="post">
							<img class="thumbnail" src="{{post.thumbnail.url}}">
							<div class="post-preview">
								<h6 class="post-title">{{ post.headline }}</h6>
								<p class="post-intro">{{ post.sub_headline}}</p>

								{% for tag in post.tags.all %}
									<span class="tag">{{tag}}</span>
								{% endfor %}
								<hr>
								<a href="{% url 'post' post.slug %}">Read More</a>
								<br>
								<br>
								<a target="_blank" href={{post.git}}>GitHub</a>

							</div>
						</div>
					</div>
					{% endfor %}
				</div>

				<p align="center">
					<a href="{% url 'posts' %}">View More</a>
				</p>
			</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<a href=""></a>
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="POST" action="{% url 'send_email' %}">
				{% csrf_token %}
				<a name="contact"></a>

				<label>Name</label>
				<input class="input-field" type="text" name="name">

				<label>Subject</label>
				<input class="input-field" type="text" name="subject">

				<label>Email</label>
				<input class="input-field" type="text" name="email">

				<label>Message</label>
				<textarea class="input-field" name="message"></textarea>

				<input id="submit-btn" type="submit" value="Send">
			</form>
		</div>
	</section> 

	<script type="text/javascript">
	 	let static = "{% static 'css' %}"
	</script>
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

src/base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Khalil Guesmi</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

</head>
<body>
{% include 'base/navbar.html' %}
{% block content %}
{% endblock content %}

</body>
</html>

src/base/templates/base/navbar.html
<div class="nav-wrapper">

    <!-- Link around dots-wrapper added after tutorial video -->
    <a href="{% url 'home' %}">
        <div class="dots-wrapper">
            <div id="dot-1" class="browser-dot"></div>
            <div id="dot-2" class="browser-dot"></div>
            <div id="dot-3" class="browser-dot"></div>
        </div>
    </a>
					

    <ul id="navigation">
        <li><a href="{% url 'home' %}#contact">Contact</a></li>

        {% if request.user.is_authenticated %}

        <li><a href="{% url 'create_post' %}">CreatePost</a></li>
        {% endif %}
    </ul>
</div>

src/base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<style type="text/css">
    img{
        max-width: 100%;
        object-fit : cover;
    }
</style>
<div style="text-align:center">
    <div class="main-container">

        <img src="{{post.thumbnail.url}} " >
        <h1>{{post.headline}}</h1>
        <h4>{{post.sub_headline}}</h4>
        <p>{{post.body|safe}}</p>
        <p>{{post.git}}</p>

    </div>
</div>
{% endblock content %}

src/base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">

<style type="text/css">
	#div_id_tags, #id_tags{
		overflow-y: scroll;
		max-height: 150px;
		border-radius: 5px;
		padding: 5px;
		border:1px solid #888;
	}
</style>

<div class="main-container">
	<h1> Posts </h1>
	<form id="searchForm" method="GET" >
		{{myFilter.form|crispy}}
		<input class="btn btn-primary" type="submit" value="search"  >
	</form>
	<br>
	<div class="post-wrapper">
		{% for post in posts %}
		<div style="text-align:center">

			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}">
				<div class="post-preview">

					<h6 class="post-title">{{ post.headline }}</h6>
					<p class="post-intro">{{ post.sub_headline}}</p>
					{% for tag in post.tags.all %}
						<span class="tag">{{tag}}</span>
					{% endfor %}
					<hr>
					<a href="{% url 'post' post.slug %}">Read More</a>
					<br>
					<br>
					<a target="_blank" href={{post.git}}>GitHub</a>
					<br>
					<br>
					{% if request.user.is_authenticated %}
					  <a href="{% url 'update_post' post.slug %}">Edit</a>
					| <a href="{% url 'delete_post' post.slug %}">Delete</a>

					{% endif %}


				</div>
			</div>
		</div>
		{%  empty %}
		<h3>no post found...</h3>
		{% endfor %}
	</div>

	<div class="row">
		{% if posts.has_other_pages %}
		<ul class="pagination">
			{% if posts.has_previous %}
				<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>
				<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
			{% endif %}
			{% for i in posts.paginator.page_range %}
				{% if post.number == i %}
					<li class="page-item"><a class="page-link">{{i}}</a></li>
				{% else %}
					<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
				{% endif %}

			{%endfor%}
			{% if posts.has_next %}
				<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>
				<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
			{% endif %}

		</ul>
		{% endif %}
	</div>
</div>
<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementByClassName('page-link')

	for(var i=0; pageLinks.length; i++)
	{
	pageLinks[i].addEventListener('click', function(e){
		e.preventDefault()
		let page =this.dataset.page
		console.log('page:', page)
		searchForm.innerHTML += <input value="${page}" name="page" hidden>
		})
	}

</script>

{% endblock content %}

src/base/templates/base/profile.html
{% extends 'base/main.html' %}
    
    
{% block content %}

<h1>profile</h1>
{% endblock content %}